### ISSUE TITLE
Documentation: How to use this in my project

### ISSUE THREAD

**Issue by Muhammadinaam** [JacksiroKe/MDI-Tabs-Control#1]

**Comment by JacksiroKe** [comment]
If you are familiar with Visual Studio you should not have a problem cloning this project and building to generate the dlls which you can then import to your project

**Comment by JacksiroKe** [comment]
Hi, I added a wiki to this project https://github.com/JacksiroKe/MdiTabCtrl/wiki and I also made it a nuget package. Check it out
